service:
  name: snap-user-api
  namespace: markti
  type: LoadBalancer
  port: 8080
  targetPort: 80
deployment:
  name: snap-user-api
  replicas: 2
  image: crb0e6jh.azurecr.io/snap-user-api:v1
  containerPort: 80